### ISSUE TITLE
Attribute Error when selecting "Mark selected for export"

### ISSUE THREAD

**Issue by oliacym** [Vertex-Rage-Studio/ue-helper#1]
When I select multiple objects in my scene and select "Mark selected for export", I recieve the error:

AttributeError: 'Object' object has no attribute 'bfu_export_type'

Image of error is attached.
![image](https://github.com/Vertex-Rage-Studio/ue-helper/assets/38333801/e2e8b8e1-8cd7-4c2d-8eae-b26af16cb233)

**Comment by VertexMachine** [comment]
Which version of ue-helper are you using?

**Comment by VertexMachine** [comment]
And which version of base "Blender for Unreal Engine" addon are you using?

**Comment by oliacym** [comment]
ue-helper is 0.06, and Blender for Unreal Engine is 0.4.1.

**Comment by VertexMachine** [comment]
Ah! Try v0.0.3 of ue-helper or upgrade BfUE to 0.4.2. BleuRaven updated variable names between those releases. I'll add this information to readme in the meantime.

**Comment by oliacym** [comment]
That seems to have done the trick, upgrading BfUE to 0.4.2 fixed the problem. Many thanks! :)

**Comment by VertexMachine** [comment]
Awesome! Glad this worked out!
